export const GET_GEO_LOCATION = "GET_GEO_LOCATION";
export const GET_GEO_COORDINATES = "GET_GEO_COORDINATES";
export const GET_SKY_TYPE = "GET_SKY_TYPE";
export const GET_API_RESPONSE = "GET_API_RESPONSE";
export const GET_DAY_RESPONSE = "GET_DAY_RESPONSE";
export const GET_FORECAST_RESPONSE = "GET_FORECAST_RESPONSE";